name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --system
      - name: Lint with Mypy
        run: mypy ballcone tools
      - name: Lint with flake8
        run: flake8
      - name: Test with unittest
        run: python3 -munittest discover
      - name: Build with PyInstaller
        run: |
          pyinstaller ballcone.spec
          dist/ballcone --version
